version: '3.8'

services:
  ocr-verify:
    build: .
    cpus: "1.0"        # Limita a 1 CPU
    mem_limit: "512m"  # Limita a 512 MB de memória
    memswap_limit: "1g" # Limita a 1 GB de memória swap
    shm_size: "64m"     # Define 64 MB para /dev/shm
    ports:
      - "7000:7000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=7000
      - UPLOAD_DIR=/app/uploads

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ocr-verify

volumes:
  uploads: