version: '3.8'

services:
  ocr-api:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=7000
      - UPLOAD_DIR=/app/uploads

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ocr-api

volumes:
  uploads: